#pragma once
#include <stdint.h>

// Anti-aliased bitmap font, generated by tools/gen_font.py.
// Coordinates are relative to the pen position on the baseline.
struct GaugeGlyph {
    uint16_t code;     // unicode codepoint
    uint8_t  w, h;     // bitmap size
    int8_t   dx;       // left bearing (pen x -> bitmap left)
    int8_t   dy;       // bitmap top, pixels ABOVE the baseline
    uint8_t  adv;      // pen advance
    uint32_t offset;   // into GaugeFont::bitmap, w*h alpha bytes
};

struct GaugeFont {
    const GaugeGlyph *glyphs;   // sorted by code
    const uint8_t    *bitmap;
    uint16_t          count;
    uint8_t           ascent;   // tallest ink above baseline
    uint8_t           descent;  // deepest ink below baseline
};
