#!/usr/bin/env python3
"""
gen_font.py — rasterize a .ttf subset into the gauge's own anti-aliased font format.

Why not TFT_eSPI .vlw smooth fonts?  TFT_eSPI blends glyph edges against a single
text-background colour. This UI draws text over a textured background image, so the
renderer (src/ui/canvas.cpp) blends each edge pixel against the *actual* pixel under it.
That needs only: per-glyph metrics + an 8-bit alpha bitmap, which is what this emits.

Usage:
  python3 gen_font.py <font.ttf> <px_size> <c_name> <chars> <out.h>
Example:
  python3 gen_font.py font_src/BarlowCondensed-Black.ttf 58 font_rpm "0123456789,-" ../src/fonts/font_rpm.h

Regenerate all fonts at once with tools/make_fonts.sh.
Requires Pillow (pip install pillow).
"""
import sys
from PIL import Image, ImageDraw, ImageFont

if len(sys.argv) != 6:
    print(__doc__)
    sys.exit(1)

ttf, size, name, chars, out = sys.argv[1], int(sys.argv[2]), sys.argv[3], sys.argv[4], sys.argv[5]
font = ImageFont.truetype(ttf, size)

glyphs = []   # (code, w, h, dx, dy_top, adv, bytes)
for ch in sorted(set(chars), key=ord):
    adv = round(font.getlength(ch))
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")     # y relative to baseline, negative = up
    if x1 <= x0 or y1 <= y0:
        glyphs.append((ord(ch), 0, 0, 0, 0, adv, b""))
        continue
    w, h = x1 - x0, y1 - y0
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, fill=255, font=font, anchor="ls")
    glyphs.append((ord(ch), w, h, x0, -y0, adv, img.tobytes()))

ascent = max(g[4] for g in glyphs)                     # tallest ink above baseline
descent = max(g[2] - g[4] for g in glyphs)             # deepest ink below baseline

bitmap = bytearray()
rows = []
for code, w, h, dx, dy, adv, data in glyphs:
    rows.append(f"  {{0x{code:04X}, {w:3d}, {h:3d}, {dx:3d}, {dy:3d}, {adv:3d}, {len(bitmap):6d}}},  // '{chr(code)}'")
    bitmap += data

with open(out, "w", encoding="utf-8") as f:
    f.write(f"// {name}: {ttf.split('/')[-1]} @ {size}px — generated by tools/gen_font.py, do not edit.\n")
    f.write("#pragma once\n#include \"ui/font.h\"\n\n")
    f.write(f"static const uint8_t {name}_bitmap[{len(bitmap)}] = {{\n")
    for i in range(0, len(bitmap), 24):
        f.write("  " + ",".join(str(b) for b in bitmap[i:i + 24]) + ",\n")
    f.write("};\n\n")
    f.write(f"static const GaugeGlyph {name}_glyphs[{len(glyphs)}] = {{\n")
    f.write("\n".join(rows).replace("'\\'", "'backslash'") + "\n};\n\n")
    f.write(f"static const GaugeFont {name} = {{ {name}_glyphs, {name}_bitmap, {len(glyphs)}, {ascent}, {descent} }};\n")

print(f"{name}: {len(glyphs)} glyphs, ascent {ascent}, descent {descent}, {len(bitmap)} bitmap bytes -> {out}")
