#!/usr/bin/env python3
"""Extract the 13 slanted shift-bar slots from the background art into src/ui/shift_slots.h,
so live segments land exactly on the painted slots. Re-run if the background changes."""
import sys
from PIL import Image
src = sys.argv[1] if len(sys.argv) > 1 else "art/bg_ice.png"
out = sys.argv[2] if len(sys.argv) > 2 else "../src/ui/shift_slots.h"
im = Image.open(src).convert("RGB")
Y0, Y1, N = 28, 47, 13
rows = []
for y in range(Y0, Y1 + 1):
    runs, start = [], None
    for x in range(0, 212):
        on = sum(im.getpixel((x, y))) > 70
        if on and start is None: start = x
        if not on and start is not None:
            runs.append((start, x - 1)); start = None
    runs = [r for r in runs if r[0] >= 9 and r[1] - r[0] >= 8]
    assert len(runs) == N, (y, runs)
    rows.append(runs)
with open(out, "w") as f:
    f.write("// Generated by tools/gen_slots.py from the background art — do not edit.\n#pragma once\n#include <stdint.h>\n\n")
    f.write(f"#define SLOT_COUNT {N}\n#define SLOT_Y0 {Y0}\n#define SLOT_ROWS {Y1 - Y0 + 1}\n\n")
    f.write("// [row][slot] = {first x, last x} (inclusive) of each painted slot on that scanline\n")
    f.write("static const uint8_t SLOT_SPAN[SLOT_ROWS][SLOT_COUNT][2] = {\n")
    for y, runs in zip(range(Y0, Y1 + 1), rows):
        f.write("  {" + ",".join(f"{{{a},{b}}}" for a, b in runs) + "},  // y=" + str(y) + "\n")
    f.write("};\n")
print("ok", out)
