#!/usr/bin/env python3
"""Convert a 320x240 PNG background to an RGB565 C header for src/assets/.

  python3 gen_bg.py <in.png> <c_name> <out.h> [--vivid AMOUNT]

--vivid (default 1.0, 0 = off) boosts saturation/brightness of the coloured accent
lines only — the carbon weave and dark panel interiors are left untouched. TFT
panels look noticeably flatter than a monitor, so the art is pre-punched here.
Requires Pillow + numpy."""
import argparse
import numpy as np
from PIL import Image

ap = argparse.ArgumentParser()
ap.add_argument("src"); ap.add_argument("name"); ap.add_argument("out")
ap.add_argument("--vivid", type=float, default=1.0)
a = ap.parse_args()

im = Image.open(a.src).convert("RGB")
assert im.size == (320, 240), im.size
if a.vivid > 0:
    hsv = np.asarray(im.convert("HSV")).astype(np.float32) / 255
    h, s, v = hsv[..., 0], hsv[..., 1], hsv[..., 2]
    # weight: 0 for greys / dark pixels, 1 for clearly coloured, lit pixels
    m = np.clip((s - 0.20) / 0.25, 0, 1) * np.clip((v - 0.18) / 0.20, 0, 1) * a.vivid
    s = np.clip(s * (1 + 0.70 * m), 0, 1)
    v = np.clip(v * (1 + 0.35 * m), 0, 1)
    im = Image.fromarray((np.stack([h, s, v], -1) * 255 + 0.5).astype(np.uint8), "HSV").convert("RGB")

raw = im.tobytes()
px = [((raw[i] >> 3) << 11) | ((raw[i + 1] >> 2) << 5) | (raw[i + 2] >> 3) for i in range(0, len(raw), 3)]
with open(a.out, "w") as f:
    f.write(f"// {a.name}: generated by tools/gen_bg.py from {a.src.split('/')[-1]} (vivid {a.vivid}) — do not edit.\n")
    f.write("#pragma once\n#include <stdint.h>\n\n")
    f.write(f"static const uint16_t {a.name}[320 * 240] = {{\n")
    for i in range(0, len(px), 16):
        f.write("  " + ",".join(f"0x{p:04X}" for p in px[i:i + 16]) + ",\n")
    f.write("};\n")
print(a.name, "->", a.out)
